type: shimValueSensor
props:
    SupportsOnState: false
    SupportsSensorValue: true
    SupportsStatusRequest: false
    adjustmentFunction: ''
    battery_payload_key: ''
    battery_payload_type: json
    message_type: '##AM2302##'
    reports_battery_status: false
    shimSensorPrecision: '2'
    shimSensorSubtype: Temperature-F
    state_dict_payload_key: .
    state_location: payload
    state_location_payload_key: temperature
    state_location_payload_type: json
    state_location_topic_field: '0'
    uid_location: topic
    uid_location_payload_key: ''
    uid_location_topic_field: '1'
trigger:
    match_list: '["Match: barn", "Match: AM2302", "Match: update", "End: "]'
    message_type: '##AM2302##'
    queueMessage: true
