type: shimOnOffSensor
message_type: '##HueRemote##'
props:
    SupportsBatteryLevel: true
    SupportsOnState: true
    battery_payload_key: battery
    battery_payload_type: json
    shimSensorSubtype: Generic
    state_dict_payload_key: .
    state_location: payload
    state_location_payload_key: action
    state_location_payload_type: json
    state_location_topic_field: '0'
    uid_location: topic
    uid_location_topic_field: '2'
trigger:
    match_list: '["Match: zigbee2mqtt", "Match: HueRemote", "Any: ", "End: "]'
    queueMessage: true
