message_type: zigbee2mqtt
type: shimDimmer
props:
    SupportsSensorValue: true
    SupportsStatusRequest: true
    action_template: zigbee2mqtt/{{uniqueID}}/set
    brightness_scale: '255'
    dimmer_action_payload: '{"state":"ON","brightness":{{brightness}}}'
    dimmer_action_template: zigbee2mqtt/{{uniqueID}}/set
    state_location: payload
    state_location_payload_key: state
    state_location_payload_type: json
    status_action_payload: '{"state":""}'
    status_action_template: zigbee2mqtt/{{uniqueID}}/set
    uid_location: topic
    uid_location_topic_field: '1'
    value_location_payload_key: brightness
trigger:
    match_list: '["Match: zigbee2mqtt", "Any: ", "End: "]'
    queueMessage: true
