message_type: zigbee2mqtt
type: shimRelay
props:
    SupportsSensorValue: true
    SupportsStatusRequest: true
    action_template: zigbee2mqtt/{{uniqueID}}/set
    off_action_payload: '{"state": "OFF"}'
    on_action_payload: '{"state": "ON"}'
    shimSensorSubtype: Power
    state_location: payload
    state_location_payload_key: state
    state_location_payload_type: json
    state_on_value: 'ON'
    status_action_payload: '{"state": ""}'
    status_action_template: zigbee2mqtt/{{uniqueID}}/get
    uid_location: topic
    uid_location_topic_field: '1'
trigger:
    match_list: '["Match: zigbee2mqtt", "Any: ", "End: "]'
    queueMessage: true
